name: Build Windows Client

on: [push, pull_request]

jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Modify config.json
        run: |
          sed -i "s#$(cat public/config.json | grep "location")/\"location\": \"desktop"#g" public/config.json;
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm run build-desktop-win
      - name: Upload Windows executable
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: 'Windows executable (output dir)'
          path: dist